version: 2
jobs:
    build:
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
    deploy:
      docker:
        - image: circleci/node:7  
      steps:
        - checkout
        - run:
            name: Deploy over SSH to Digital Ocean
            command: |
              ssh $SSH_USER@$SSH_HOST -o StrictHostKeyChecking=no 'cd blade-express/; git checkout master; git pull; yarn; yarn start;'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master