version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    environment:
      NODE_ENV: "test"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --production=false
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Set access to setup-kubectl.sh
          command: |
            chmod +x ./.circleci/setup-kubectl.sh
      - run:
          name: Setup kubectl
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
      - run:
          name: Set access to kubernetes.sh
          command: |
            chmod +x ./.circleci/kubernetes.sh
      - run:
          name: Run kubectl deployment and service setup
          command: |
            ssh $SSH_USER@$SSH_HOST -o StrictHostKeyChecking=no 'bash -s' < ./.circleci/kubernetes.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: kubernetes
